package controllers;

import javafx.fxml.FXML;

import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.control.TextField;

import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ResourceBundle;

import Model.Employe;
import application.ConnexionMysql;
import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.TableView;
import javafx.scene.Parent;
import javafx.scene.control.DatePicker;
import javafx.scene.control.TableColumn;
import javafx.scene.layout.Pane;


public class InterfaceListeEmpController implements Initializable{
	@FXML
	private AnchorPane contentPane;
	@FXML
	private Pane btn_create;
	@FXML
	private TableView Table;
	@FXML
	private ImageView btn_return;
	@FXML
	private DatePicker Date;
	@FXML
	private TextField txt_chercher;
	
	  @FXML
	    private TableColumn<?, ?> col_DateNaissance;

	    @FXML
	    private TableColumn<?, ?> col_action;

	    @FXML
	    private TableColumn<?, ?> col_departement;

	    @FXML
	    private TableColumn<?, ?> col_email;

	    @FXML
	    private TableColumn<?, ?> col_fonction;

	    @FXML
	    private TableColumn<?, ?> col_nom;

	    @FXML
	    private TableColumn<?, ?> col_prenom;

	    @FXML
	    private TableColumn<?, ?> col_telephone;

	// Event Listener on Pane[#btn_create].onDragDetected
	@FXML
	public void AjouterEmploye(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TableView[#Table].onSort

    @FXML
    void ListeEmp(ActionEvent event) {
        loadDataFromDatabase();
    }
    public void loadDataFromDatabase() {
        Connection conn = ConnexionMysql.connexionDB();

        if (conn != null) {
            try {
                PreparedStatement statement = conn.prepareStatement("SELECT * FROM employe");
                ResultSet rs = statement.executeQuery();

                while (rs.next()) {
                    String nom = rs.getString("nom");
                    String prenom = rs.getString("prenom");
                    Date DateNaissance = rs.getDate("dateNaissance");
                    String departement = rs.getString("departement");
                    String email = rs.getString("email");
                    String telephone = rs.getString("telephon");
                    String fonction = rs.getString("fonction");

                    // Création de l'objet Employe avec les données récupérées
                    Employe emp = new Employe(nom, prenom, DateNaissance, departement, email, telephone, fonction);

                    // Ajout de l'employé à la TableView
                    Table.getItems().add(emp);
                }

                rs.close();
                statement.close();
                conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
                // Gérer l'erreur de données ici
            }
        } else {
            System.out.println("La connexion à la base de données a échoué.");
        }
    }


	   private void loadFXML(String fxmlFileName) {
	        try {
	            FXMLLoader loader = new FXMLLoader(getClass().getResource(fxmlFileName));
	            Parent root = loader.load();
	            contentPane.getChildren().setAll(root); // Remplacez le contenu actuel par la nouvelle vue chargée
	        } catch (IOException e) {
	            e.printStackTrace();
	        }
	    }
	// Event Listener on ImageView[#btn_return].onDragDetected
	    //retourn à l'autre page
	    @FXML
	    void back() {
	        loadFXML("/interfaces/DashoboardAdmin.fxml");

	    }

	// Event Listener on DatePicker[#Date].onAction
	@FXML
	public void TrierParDate(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#txt_chercher].onAction
	@FXML	public void Search(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
}
